package vista.InternalFrameInventario;

import controlador.Ctrl_Usuario;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Usuario;
import static vista.InternalFrameInventario.InternalVerUsuarios.visor;

/**
 *
 * @author Andy_T
 */
public class InternalActualizarUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalActualizarUsuario
     */
    public InternalActualizarUsuario() {
        initComponents();
        this.setSize(new Dimension(700, 275));
        this.setTitle("Editar Usuario");
        setText();
    }

    public void setText() {
        int selectedRowIndex = visor.getSelectedRow();
        if (selectedRowIndex != -1) {

            //LLAMAMOS A LA TABLA
            DefaultTableModel model = (DefaultTableModel) visor.getModel();

            //OBTENEMOS LA SELECCION DE LA TABLA 
            String nombre;
            String contrasena;
            String direccion;
            String telefono;

            nombre = model.getValueAt(selectedRowIndex, 1).toString();
            contrasena = model.getValueAt(selectedRowIndex, 2).toString();
            direccion = model.getValueAt(selectedRowIndex, 3).toString();
            telefono = model.getValueAt(selectedRowIndex, 4).toString();

            //LLENAR DATOS EN LOS TXT
            Txt_nombre.setText(nombre);
            Txt_contrasena.setText(contrasena);
            Txt_direccion.setText(direccion);
            Txt_telefono.setText(telefono);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Btn_Acutalizar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Txt_nombre = new javax.swing.JTextField();
        Txt_telefono = new javax.swing.JTextField();
        Txt_direccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Txt_contrasena = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 2, 24)); // NOI18N
        jLabel1.setText("Editar Usuario");

        Btn_Acutalizar.setFont(new java.awt.Font("Bodoni MT", 2, 24)); // NOI18N
        Btn_Acutalizar.setText("Editar");
        Btn_Acutalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AcutalizarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Bodoni MT", 2, 24)); // NOI18N
        jLabel6.setText("Nombre:");

        jLabel7.setFont(new java.awt.Font("Bodoni MT", 2, 24)); // NOI18N
        jLabel7.setText("Telefono:");

        jLabel8.setFont(new java.awt.Font("Bodoni MT", 2, 24)); // NOI18N
        jLabel8.setText("Direccion:");

        jLabel9.setFont(new java.awt.Font("Bodoni MT", 2, 24)); // NOI18N
        jLabel9.setText("Contraseña:");

        Txt_contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_contrasenaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Txt_contrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(Txt_telefono)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(Btn_Acutalizar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel1)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(Btn_Acutalizar)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_AcutalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AcutalizarActionPerformed
        Usuario usuario = new Usuario();
        Ctrl_Usuario controlUsuario = new Ctrl_Usuario();

        if (Txt_nombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene el campo Nombre");
        } else if (Txt_contrasena.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene el campo Contraseña");
        } else if (Txt_direccion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene el campo Dirección");
        } else if (Txt_telefono.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene el campo de Teléfono");

        } else if (Txt_telefono.getText().length() > 10) {
            JOptionPane.showMessageDialog(null, "El campo Teléfono deben tener 10 dígitos");
        } else if (!Txt_telefono.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "El campo Télefono solo acepta números");
        } else {
            usuario.setNombre(Txt_nombre.getText().trim());
            usuario.setContrasena(Txt_contrasena.getText());
            usuario.setDireccion(Txt_direccion.getText());
            usuario.setTelefono(Txt_telefono.getText());

            int selectedRowIndex = visor.getSelectedRow();
            // SELECCCIONAR FILA DE LA TABLA
            if (selectedRowIndex != -1) {

                //LLAMAMOS A LA TABLA
                DefaultTableModel model = (DefaultTableModel) visor.getModel();

                //OBTENEMOS LA SELECCION DE LA TABLA 
                int id;
                id = Integer.parseInt(model.getValueAt(selectedRowIndex, 0).toString());

                //SETIAMOS EL ID OBTENIDO
                usuario.setIdUsuario(id);

                //LLAMAMOS AL CONTROLADOR
                if (controlUsuario.editar(usuario, id)) {
                    JOptionPane.showMessageDialog(null, "Usuario Editado");
                    visor.clearSelection();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Error al editar");

                }
            }
        }

    }//GEN-LAST:event_Btn_AcutalizarActionPerformed

    private void Txt_contrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_contrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_contrasenaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Acutalizar;
    private javax.swing.JTextField Txt_contrasena;
    private javax.swing.JTextField Txt_direccion;
    private javax.swing.JTextField Txt_nombre;
    private javax.swing.JTextField Txt_telefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
